# Generated by Django 4.1 on 2022-08-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('monthly_rent', models.IntegerField()),
                ('vehicle_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('joining_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('rent_type', models.CharField(max_length=10)),
                ('fix_rent', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
