# Generated by Django 4.1 on 2022-08-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='rent_type',
            field=models.CharField(choices=[('One sided', 'One sided'), ('Two sided', 'Two sided')], max_length=10),
        ),
    ]
