# Generated by Django 4.1 on 2022-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_passenger_rent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('another', 'another')], max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='rent_type',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('another', 'another')], max_length=10),
        ),
    ]
