# Generated by Django 4.1 on 2022-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
