# Generated by Django 4.1 on 2022-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_alter_passenger_rent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='fix_rent',
            field=models.IntegerField(default=0),
        ),
    ]
