# Generated by Django 4.1 on 2022-08-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_month', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
                ('rent', models.PositiveIntegerField()),
                ('total_expense_provider', models.IntegerField()),
                ('total_expense_vehicle', models.IntegerField()),
                ('total_local_rent', models.IntegerField()),
                ('final_rent', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rent', models.IntegerField()),
                ('rent_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.passenger')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.rent')),
            ],
        ),
        migrations.CreateModel(
            name='LocalRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_rent', models.IntegerField()),
                ('date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
