# Generated by Django 4.1 on 2022-08-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='expense_month',
            field=models.IntegerField(choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')]),
        ),
        migrations.AlterField(
            model_name='rentdetail',
            name='rent_type',
            field=models.CharField(choices=[('one sided', 'one sided'), ('two sided', 'two sided')], max_length=50),
        ),
    ]
