# Generated by Django 4.1 on 2022-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_rent_expense_month_alter_rentdetail_rent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='final_rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_expense_provider',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_expense_vehicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_local_rent',
            field=models.IntegerField(default=0),
        ),
    ]
